FROM mcr.microsoft.com/devcontainers/javascript-node:1-20
RUN curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.17/2023-05-11/bin/darwin/amd64/kubectl && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
